package tinygolexer

import (
	"bytes"
	"fmt"
	"html/template"
	"log"
)

const codeTemplate = `// Generated by github.com/imagine243/tinygolexer
// do edit it

package {{.PackageName}}

`

type fileModel struct {
	PackageName string
}

func Generate(fileName string, token []Token) {
	lexTp, err := template.New("lexfile").Parse(codeTemplate)
	if err != nil {
		log.Fatal(err)
		return
	}

	var model fileModel
	model.PackageName = fileName

	var bf bytes.Buffer
	err = lexTp.Execute(&bf, &model)
	if err != nil {
		log.Fatal(err)
		return
	}

	fmt.Printf(bf.String())
}
